import { useState, useEffect } from 'react';
import { analyzePageSimilarity as analyzeSimilarity } from '../utils/pageSimilarityUtils.js';
import { extractDatesFromText } from '../utils/dateDetectionUtils.js';

export const useSimilarityManagement = (fileURL, pages, open) => {
  const [similarPages, setSimilarPages] = useState({});
  const [pageTemplates, setPageTemplates] = useState({});
  const [isAnalyzingSimilarity, setIsAnalyzingSimilarity] = useState(false);
  const [pdfjsLib, setPdfjsLib] = useState(null);

  // Cargar pdfjsLib dinámicamente
  useEffect(() => {
    import('../../../config/pdfConfig.js').then(module => {
      setPdfjsLib(module.pdfjsLib);
    }).catch(err => {
      console.error('Error cargando pdfConfig:', err);
      setPdfjsLib(null);
    });
  }, []);

  // Analizar similitud automáticamente cuando se cargan las páginas
  useEffect(() => {
    if (pages.length > 0 && !isAnalyzingSimilarity && pdfjsLib) {
      // Pequeño delay para asegurar que las páginas estén completamente cargadas
      setTimeout(() => {
        analyzePageSimilarity();
      }, 1000);
    }
  }, [pages.length, pdfjsLib]);

  // Función para analizar similitud de páginas
  const analyzePageSimilarity = async () => {
    await analyzeSimilarity(pdfjsLib, fileURL, pages, setIsAnalyzingSimilarity, setPageTemplates, setSimilarPages);
  };

  // Detectar páginas similares automáticamente al abrir el modal
  useEffect(() => {
    if (open && pages.length > 0 && Object.keys(similarPages).length === 0) {
      console.log('🚀 Iniciando detección automática de páginas similares...');
      analyzePageSimilarity();
    }
  }, [open, pages.length, similarPages]);

  // Función para obtener páginas similares a una página
  const getSimilarPageNumbers = (pageNum) => {
    return similarPages[pageNum] || [];
  };

  // Función para detectar y crear grupos automáticamente basados en similitud
  const createAutoGroups = (numPages, createMultipleAutoGroups) => {
    if (Object.keys(similarPages).length === 0) return;
    
    console.log('🤖 Iniciando detección automática de grupos...');
    
    // Crear grupos automáticos basados en similitud
    const processedPages = new Set();
    let groupCounter = 1;
    const groupsToCreate = [];

    for (let pageNum = 1; pageNum <= numPages; pageNum++) {
      if (processedPages.has(pageNum)) continue;
      
      // Obtener páginas similares a esta
      const similarPageNumbers = similarPages[pageNum] || [];
      
      if (similarPageNumbers.length > 0) {
        // Crear grupo con la página actual y sus similares
        const groupPages = [pageNum, ...similarPageNumbers].sort((a, b) => a - b);
        
        // Verificar si alguna página ya está en un grupo existente
        const existingGroup = pageGroups.find(group => 
          groupPages.some(page => group.pages.includes(page))
        );
        
        if (!existingGroup) {
          // Preparar nuevo grupo automático
          const newGroup = {
            id: `auto-${groupCounter}`,
            name: `Grupo Auto ${groupCounter}`,
            pages: groupPages,
            date: null,
            isAutoGenerated: true
          };
          
          groupsToCreate.push(newGroup);
          console.log(`🤖 Grupo automático ${groupCounter} preparado:`, groupPages);
          groupCounter++;
        }
        
        // Marcar páginas como procesadas
        groupPages.forEach(page => processedPages.add(page));
      }
    }
    
    // Crear todos los grupos de una vez
    if (groupsToCreate.length > 0) {
      createMultipleAutoGroups(groupsToCreate);
    }
    
    console.log('✅ Detección automática de grupos completada');
  };

  // Función para analizar patrones del grupo creado por el usuario y crear grupos automáticos
  const analyzeUserGroupPatterns = async (pageGroups, numPages, createMultipleAutoGroups, fileURL) => {
    console.log('🔍 Analizando patrones del grupo creado por el usuario...');
    
    if (!pdfjsLib) {
      console.log('❌ pdfjsLib no disponible');
      return;
    }
    
    // Obtener el último grupo creado (no automático)
    const userGroups = pageGroups.filter(group => !group.isAutoGenerated);
    if (userGroups.length === 0) return;
    
    const lastUserGroup = userGroups[userGroups.length - 1];
    console.log('📋 Grupo del usuario a analizar:', lastUserGroup);
    
    // Obtener páginas ya utilizadas en grupos
    const usedPages = new Set();
    pageGroups.forEach(group => {
      group.pages.forEach(pageNum => usedPages.add(pageNum));
    });
    
    // Obtener páginas disponibles (no utilizadas en grupos)
    const availablePages = [];
    for (let i = 1; i <= numPages; i++) {
      if (!usedPages.has(i)) {
        availablePages.push(i);
      }
    }
    
    console.log('📄 Páginas disponibles para análisis:', availablePages);
    
    if (availablePages.length === 0) {
      console.log('⚠️ No hay páginas disponibles para crear grupos automáticos');
      return;
    }
    
    // Analizar patrones del grupo del usuario
    const patterns = await analyzeGroupPatterns(lastUserGroup, pages, fileURL);
    console.log('🎯 Patrones detectados:', patterns);
    
    // Buscar páginas con patrones similares
    const similarGroups = await findSimilarGroups(patterns, availablePages, pages, similarPages, fileURL);
    console.log('🤖 Grupos similares encontrados:', similarGroups);
    
    // Crear grupos automáticos basados en patrones
    if (similarGroups.length > 0) {
      createMultipleAutoGroups(similarGroups);
    }
  };

  // Función para analizar patrones de un grupo específico
  const analyzeGroupPatterns = async (group, pages, fileURL) => {
    const patterns = {
      dates: [],
      identifiers: [],
      moneyAmounts: [],
      textPatterns: []
    };
    
    // Analizar cada página del grupo
    for (const pageNum of group.pages) {
      try {
        // Obtener el objeto PDF real
        const pdf = await pdfjsLib.getDocument(fileURL).promise;
        const pdfPage = await pdf.getPage(pageNum);
        const textContent = await pdfPage.getTextContent();
        const fullText = textContent.items.map(item => item.str).join(' ');
        
        // 1. Analizar fechas
        const dates = extractDatesFromText(fullText);
        patterns.dates.push(...dates);
        
        // 2. Buscar identificadores de página (página X/Y, página X de Y, etc.)
        const pageIdPatterns = [
          /página\s+(\d+)\s*\/\s*(\d+)/gi,
          /página\s+(\d+)\s+de\s+(\d+)/gi,
          /page\s+(\d+)\s*\/\s*(\d+)/gi,
          /page\s+(\d+)\s+of\s+(\d+)/gi,
          /hoja\s+(\d+)\s*\/\s*(\d+)/gi
        ];
        
        pageIdPatterns.forEach(pattern => {
          const matches = fullText.match(pattern);
          if (matches) {
            patterns.identifiers.push(...matches);
          }
        });
        
        // 3. Buscar montos de dinero ($, €, pesos, etc.)
        const moneyPatterns = [
          /\$\s*[\d,]+\.?\d*/g,
          /€\s*[\d,]+\.?\d*/g,
          /pesos?\s*[\d,]+\.?\d*/gi,
          /total\s*:?\s*[\d,]+\.?\d*/gi,
          /importe\s*:?\s*[\d,]+\.?\d*/gi
        ];
        
        moneyPatterns.forEach(pattern => {
          const matches = fullText.match(pattern);
          if (matches) {
            patterns.moneyAmounts.push(...matches);
          }
        });
        
        // 4. Buscar patrones de texto específicos (factura, recibo, comprobante, etc.)
        const textPatterns = [
          /factura/gi,
          /recibo/gi,
          /comprobante/gi,
          /ticket/gi,
          /voucher/gi,
          /invoice/gi
        ];
        
        textPatterns.forEach(pattern => {
          const matches = fullText.match(pattern);
          if (matches) {
            patterns.textPatterns.push(...matches);
          }
        });
        
      } catch (error) {
        console.error('Error analizando página', pageNum, error);
      }
    }
    
    // Filtrar patrones únicos y frecuentes
    return {
      dates: [...new Set(patterns.dates)],
      identifiers: [...new Set(patterns.identifiers)],
      moneyAmounts: [...new Set(patterns.moneyAmounts)],
      textPatterns: [...new Set(patterns.textPatterns)]
    };
  };

  // Función para encontrar grupos similares basados en patrones
  const findSimilarGroups = async (patterns, availablePages, pages, similarPages, fileURL) => {
    const similarGroups = [];
    const processedPages = new Set();
    
    for (const pageNum of availablePages) {
      if (processedPages.has(pageNum)) continue;
      
      try {
        // Obtener el objeto PDF real
        const pdf = await pdfjsLib.getDocument(fileURL).promise;
        const pdfPage = await pdf.getPage(pageNum);
        const textContent = await pdfPage.getTextContent();
        const fullText = textContent.items.map(item => item.str).join(' ');
        
        let similarityScore = 0;
        const matchingPages = [pageNum];
        
        // Verificar coincidencias con patrones
        if (patterns.dates.length > 0) {
          const pageDates = extractDatesFromText(fullText);
          const commonDates = patterns.dates.filter(date => pageDates.includes(date));
          if (commonDates.length > 0) similarityScore += 2;
        }
        
        if (patterns.moneyAmounts.length > 0) {
          const hasMoneyPattern = patterns.moneyAmounts.some(money => 
            fullText.toLowerCase().includes(money.toLowerCase())
          );
          if (hasMoneyPattern) similarityScore += 2;
        }
        
        if (patterns.textPatterns.length > 0) {
          const hasTextPattern = patterns.textPatterns.some(text => 
            fullText.toLowerCase().includes(text.toLowerCase())
          );
          if (hasTextPattern) similarityScore += 1;
        }
        
        // Si tiene suficiente similitud, buscar páginas relacionadas
        if (similarityScore >= 2) {
          // Buscar páginas similares (usando el sistema existente)
          const similarPageNumbers = similarPages[pageNum] || [];
          const availableSimilarPages = similarPageNumbers.filter(p => 
            availablePages.includes(p) && !processedPages.has(p)
          );
          
          if (availableSimilarPages.length > 0) {
            matchingPages.push(...availableSimilarPages);
          }
          
          // Solo crear grupo si hay al menos 2 páginas
          if (matchingPages.length >= 2) {
            similarGroups.push({
              pages: matchingPages.sort((a, b) => a - b),
              score: similarityScore,
              patterns: {
                dates: patterns.dates,
                money: patterns.moneyAmounts,
                text: patterns.textPatterns
              }
            });
            
            matchingPages.forEach(p => processedPages.add(p));
          }
        }
        
      } catch (error) {
        console.error('Error analizando página para similitud', pageNum, error);
      }
    }
    
    return similarGroups;
  };

  // Función para crear grupos basados en patrones
  const createPatternBasedGroups = (similarGroups, createMultipleAutoGroups) => {
    let groupCounter = 1;
    const groupsToCreate = [];
    
    similarGroups.forEach(groupData => {
      const newGroup = {
        id: `pattern-${groupCounter}`,
        name: `Grupo Patrón ${groupCounter}`,
        pages: groupData.pages,
        date: null,
        isAutoGenerated: true,
        isPatternBased: true,
        patterns: groupData.patterns,
        similarityScore: groupData.score
      };
      
      groupsToCreate.push(newGroup);
      groupCounter++;
    });
    
    if (groupsToCreate.length > 0) {
      createMultipleAutoGroups(groupsToCreate);
      console.log(`✅ Creados ${groupsToCreate.length} grupos basados en patrones del usuario`);
    }
  };

  return {
    similarPages,
    setSimilarPages,
    pageTemplates,
    setPageTemplates,
    isAnalyzingSimilarity,
    setIsAnalyzingSimilarity,
    analyzePageSimilarity,
    getSimilarPageNumbers,
    createAutoGroups,
    analyzeUserGroupPatterns
  };
};
